# Script convert audio files generated by single_key_wav.py to a 
# taget format. Requires ffmpeg to be installed.

for audio_file in audio_*.wav; do
    # Convert wav to mp3
    output_file="${audio_file%.wav}.mp3"
    ffmpeg -y -nostdin -hide_banner -loglevel error \
        -i $audio_file $output_file
    echo "Done $audio_file"
done
